[gdrive]
type = drive
client_id = 1064199577161-a8k2j10s4kek08993ltk2sn6ri0novl2.apps.googleusercontent.com
client_secret = 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
token = {"access_token":"ya29.a0AdMD6Eg_Ii40DShea56SiGsQ8UpVh7mpUhDadgRhbHESwZWpOuZFQGgCCFtctMqyWRANJ4-cdfJFApCZ24fr8mPsq3hILEI_xmxHPiiRuYS7njauzDviOiKLOLYw8kJ5g4J5j4jAUNA6dL5dkZsGV0OUOLvdGXj3Ikd9NPuV79Y1KZhaVmnREYHZAXpAexIvPOB3weQhaCgYKAcwSARASFQHGX2Mi--4KYu9whUsLUScPzupXeQ0207","token_type":"Bearer","refresh_token":"1//035OH1q6ghmBPCgYIARAAGAMSNwF-L9IrD2JVhaHcVLgPCfIDuOzQIUl4wC62y3m4Nj8c9a66x7oDen0IEE35MLrKhkG8YsvIH94","expiry":"2026-08-17T09:21:54.614984715Z","expires_in":3599}
team_drive = 

