# docker-compose.yml
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - "5672:5672"   # AMQP протокол
        - "15672:15672" # Веб-интерфейс управления
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
      - internal 
      - public 
  
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d  # Путь исправлен
    networks:
      - internal  

  gmail-service:
    build: ./gmail-service 
    container_name: gmail-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal
      - public
  payment-service:
    build: ./payment-service 
    container_name: payment-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal
      - public

  auth-service:
    build: ./auth
    container_name: auth-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal
  tg-service:
    build: ./telegram-bot
    container_name: tg-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal
      - public
networks:
  internal:
    driver: bridge
    internal: true  
  public: 
    driver: bridge

volumes:
  postgres_data:  
  rabbitmq_data: